import Anthropic from '@anthropic-ai/sdk';
import { log } from './logger.js';

export async function reviewGame(apiKey, gameCode, genre, theme, modifier, npcScore) {
  const client = new Anthropic({ apiKey });
  const startTime = Date.now();

  log({
    type: 'review', genre, theme, modifier, status: 'generating',
    message: `Reviewing game: ${genre} + ${theme} (score: ${npcScore})`,
    model: 'claude-haiku-4-5-20251001',
  });

  const prompt = `You are a game critic reviewing a mini-game in an arcade. The game was generated by AI.

Game genre: ${genre}
Theme: ${theme}
${modifier ? `Modifier: ${modifier}` : ''}
NPC player scored: ${npcScore} points

Here is the game's source code:
\`\`\`javascript
${gameCode.slice(0, 4000)}
\`\`\`

Review this game. Respond in JSON only:
{
  "rating": <1-5 integer, how fun/polished is this game>,
  "isBroken": <true if game crashes, freezes, or is unplayable>,
  "feedback": "<1 sentence summary of the game quality>",
  "suggestions": ["<specific actionable improvement 1>", "<specific actionable improvement 2>"]
}

Be honest. If the game is broken or unplayable, say so. If it works but isn't fun, rate it low. Max 2 suggestions.`;

  const response = await client.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 300,
    messages: [{ role: 'user', content: prompt }],
  });

  const text = response.content[0].text;
  try {
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error('No JSON in response');
    const result = JSON.parse(jsonMatch[0]);
    log({
      type: 'review', genre, theme, modifier, status: 'done',
      message: `Review done: ${genre} + ${theme} → ${result.rating}★ ${result.isBroken ? '(BROKEN)' : ''}`,
      duration: Date.now() - startTime,
      title: `${result.rating}★ — ${result.feedback}`,
    });
    return result;
  } catch (e) {
    console.error('Failed to parse review:', text);
    log({
      type: 'review', genre, theme, modifier, status: 'error',
      message: `Review parse failed: ${genre} + ${theme}`,
      duration: Date.now() - startTime,
      error: e.message,
    });
    return { rating: 3, isBroken: false, feedback: 'Review failed to parse', suggestions: [] };
  }
}
