import Anthropic from '@anthropic-ai/sdk';
import { log, addLogUpdate } from './logger.js';

export async function reviewGame(apiKey, gameCode, genre, theme, modifier, npcScore) {
  const client = new Anthropic({ apiKey });
  const startTime = Date.now();

  const logEntry = {
    type: 'review', genre: genre || 'unknown', theme: theme || 'unknown', modifier, status: 'generating',
    message: `Reviewing: ${genre} + ${theme} (score: ${npcScore})`,
    model: 'claude-haiku-4-5-20251001',
    prompt: '', // will fill after building prompt
    response: '',
  };
  log(logEntry);

  const codeToReview = gameCode.length > 12000 ? gameCode.slice(0, 12000) + '\n// ... (code continues)' : gameCode;

  const prompt = `You are a game critic reviewing a mini-game in an arcade. The game was generated by AI and runs in a Canvas2D sandbox.

Game genre: ${genre}
Theme: ${theme}
${modifier ? `Modifier: ${modifier}` : ''}
NPC player scored: ${npcScore} points

Here is the game's source code:
\`\`\`javascript
${codeToReview}
\`\`\`

${gameCode.length > 12000 ? 'NOTE: Code was truncated for review. Do NOT mark the game as broken just because code appears cut off — judge based on the logic you CAN see.' : ''}

Review this game based on the code quality and the NPC score. Respond in JSON only:
{
  "rating": <1-5 integer, how fun/polished is this game>,
  "isBroken": <true ONLY if you see clear bugs like undefined variables, infinite loops, or missing startGame function — NOT just because code is long>,
  "feedback": "<1 sentence summary>",
  "suggestions": ["<specific improvement 1>", "<specific improvement 2>"]
}

A score of 0 might mean the NPC was bad at the game, not that the game is broken. Only mark isBroken if the CODE itself has clear errors.`;

  addLogUpdate(logEntry.id, { prompt: prompt.slice(0, 2000), promptLength: prompt.length });

  const response = await client.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 500,
    messages: [{ role: 'user', content: prompt }],
  });

  const text = response.content[0].text;
  try {
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error('No JSON in response');
    const result = JSON.parse(jsonMatch[0]);
    addLogUpdate(logEntry.id, {
      status: 'done',
      duration: Date.now() - startTime,
      title: `${result.rating}★ — ${result.feedback}`,
      response: text,
    });
    return result;
  } catch (e) {
    console.error('Failed to parse review:', text);
    addLogUpdate(logEntry.id, {
      status: 'error',
      duration: Date.now() - startTime,
      error: e.message,
      response: text,
    });
    return { rating: 3, isBroken: false, feedback: 'Review failed to parse', suggestions: [] };
  }
}
